### ISSUE TITLE
Scorej-Oni is not a dlc character.

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#11]
despite being added to the game at around the same time, Scorej-Oni does not actually require the moonspell dlc to unlock, and in fact can be acquired through just the base game. Assuming the blue background for the icons of those characters and weapons is supposed to indicate what dlc they're from, then Scorej-Oni shouldn't have it.

**Comment by Danmer** [comment]
Thanks! You're right. Fixed.
