### ISSUE TITLE
Display error when combining Silent Old Sanctuary and fusion weapons.

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#14]
When combined with silent old sanctuary, Phieraggi and Vandalier leave an open weapon slot in the adjacent slot, rather than an X. Fuwalafuwaloo does not.

**Comment by wraith309** [comment]
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/5ac45aba-0651-45c8-aaff-43553f36c0ff)
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/b3565ed6-e3a7-4a61-9d21-a4d5bace7a5e)
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/fa3288cc-3fb1-426a-9bbf-ed2239fd0c56)

**Comment by Danmer** [comment]
Yeah, you have to have extra weapon slots to get all the weapons required for the evolution. With one exception, that wasn't taken into account - Smith with Vandalier by default.

Now it's fixed. Fuwalafuwaloo needs one extra slot, and also Spell Storm - two extra slots.

Thanks for pointing that out, @wraith309!
