### ISSUE TITLE
Add scaling synergies and arcana synergies to glass fandango and it's evolution.

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#19]
The Items they scale with are:
Spinach (might)
Candlabra (area)
Tome (cooldown)
Duplicator (amount)
Box (area + might)
Silver Ring (area)
Adademy Badge (amount)

The evolution specifically scales with the Arcana:
XVI Slash
XII Out of Bounds

**Comment by wraith309** [comment]
The evolution also can crit by default, so it scales with clover.

**Comment by Danmer** [comment]
@wraith309 I trust you, but where is this information from? I couldn't find anything on wiki or info-bot...

**Comment by wraith309** [comment]
I certainly don't blame you for hitting me with that "citation needed"
I couldn't find an online listing of all the synergies either, so i decided to just figure it out the old fashioned way before i posted that list. so the short answer to your question is i pulled them out of my ass, but i had a bit more logic for it than that.

for the Arcana, the game does tell you when selecting an Arcana which weapons they synergize with and the only ones with icons for the weapon are **Out of bounds** and **Slash**. Both of them point out the upgraded form specifically. I _assume_ this is referring to how upgrading the weapon freezes enemies (which causes out of bounds to trigger) buffs the clock powerup (which out of bounds cause to appear more often) and gives you crit chance, (which slash buffs)

On the topic of stat buffs:
**Might:**		all weapons are affected by might unless they explicitly say otherwise. also it's easy to test, and increasing might definitely made me do more damage
**Speed:**		the weapon description says it ignores this stat
**Duration:**	the weapon description says it ignores this stat
**Area:**		All weapons are affected by Area unless they explicitly say otherwise. Even easier to test than might. "is the attack bigger than when i started"
**Cooldown:**	Literally every weapon wants this. easily testable. just start a game using the weapon with and without silent old sanctuary
**Amount:**		so far, only aura effects like song of manna, garlic, and bocce have ignored amount. also it's easy to test, the amount of attacks come out in little pulses that are easily countable

on the slightly more complicated utility and defensive stats:
**Luck:**		All weapons with crit chance have luck scaling that increases chance to crit (also this weapon has the added benefit of luck causing it to get more powerful indirectly because of luck causing more clock powerups to spawn)
**Movespeed:**	This is the only one that wasn't trivial to test, but it doesn't even matter if its damage scales with movespeed or not because it's already highlighted in gold due to being the evolution requirement.
**Others:**		For the rest of the defensive or utility stats, it's reasonably safe to assume that if the weapon scaled with those stats the game would tell you in the item descriptions. so no scaling on Max HP, Recovery, Armor, Magnet, Growth, Greed, or Curse

Which is why i said that Glass fandango pairs with
Might, Area, Cooldown, and Amount,
and evolving Celestial Voulge makes it gain synergy with
Luck, Slash, and Out of Bounds

**Comment by Danmer** [comment]
Makes sense. Thanks for the detailed explanation.
