### ISSUE TITLE
Screen Vanishes

### ISSUE THREAD

**Issue by MushFunGus** [Danmer/vs-build-planner#20]
At first I thought it was a McCoy Oni issue, but actually, if Bocce is selected on any character along with XX silent old sanctuary, the screen blanks.

**Comment by wraith309** [comment]
I've had this issue too. I've found that it triggers specifically when bocce and an X are on the planner at the same time. so if you select SoS _after_ you've filled in all of your weapon slots then the bug doesn't trigger.

**Comment by Danmer** [comment]
Thank you for the report, guys! Indeed, my previous quick fix of the Silent Sanctuary hadn't been tested properly and added some new bugs including this one. I hope the new algorithm will work well. It fixes the reported problems and covers some other cases:
- no extra slots if there is no selected character
- Pugnala and Eleanor don't need extra slots to evolve their weapons
- Rose and Smith don't need extra slots for their unions
- adding extra slots if there are only unions (Birds, Guns, Spells, Whips)
- characters without slot-weapons don't add extra slots (Trouser, Cosmo, Megamenya, Scorej)
