### ISSUE TITLE
Gold Highlighting missing for most Non-DLC Weapon Upgrades

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#22]
When mousing over most passive items, upgraded weapon forms will not be highlighted unless you are hovering over Empty Tome, Hollow Heart, or Wings.

![image](https://github.com/Danmer/vs-build-planner/assets/38050849/4a5ba74d-3339-4391-941c-d93ffeb6587a)

like this but for pretty much every base game weapon upgrade aside from Holy Wand, Valkyrie Turner, and Bloody Tear

**Comment by wraith309** [comment]
I hope that I'm not getting too presumptuous by submitting all these issues.
I just think this tool is great, and I figure if I don't know how to program then the least I can do is submit bug reports that are as clear as possible.

**Comment by Danmer** [comment]
> I hope that I'm not getting too presumptuous by submitting all these issues.

What are you talking about. It's awesome that there is someone who cares about this tool and has time, sharp eye and understanding of how to improve it. I appreciate your help very much!
