### ISSUE TITLE
Add Emergency Meeting DLC content

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#24]
I figured I'd wait until i had some help to provide before submitting this, since I assume you are aware of the DLC and just hadn't added it because the wiki is barren of information.

so I've taken the liberty of gathering it. This was from a combination of looking at the character pages in-game, examining the Limit break stat increases for the weapons to see what stats they used, and discussing on the community discord to see if there were pieces of info that i missed.

Starting with the Characters:

**Comment by wraith309** [comment]
Crewmate Dino
	Weapon:	
		Report!
	Stats:
		Improved Movespeed
		Gains a noticeable increase to a random stat aside from greed and curse upon maxing a weapon or passive.

Engineer Gino
	Weapon:
		Lucky Swipe
	Stats:	
		Improved Movespeed

Ghost Lino
	Weapon:	
		Lifesign Scan
	Stats:	
		Improved Luck
		Improved Max Health
		Reduced Might
		
Shapeshifter Nino
	Weapon:	
		Just Vent
	Stats:	
		Improved Recovery
		Improved Movespeed
	
Guardian Pina
	Weapon:	
		Clear Debris
	Stats:	
		Improved Recovery
		Improved Armor
		Improved Movespeed
		Improved Revival
	
Impostor Rina
	Weapon:	
		Sharp Tongue
	Stats:	
		Improved Max Health
		Improved Movespeed
		Improved Might
	
Scientist Mina
	Weapon:	
		Science Rocks
	Stats:	
		Reduced __Luck__
		on levels 10, 20, 30, 40, and 50 choose an infinitely scaling level up bonus to one of the following:
		Improved Might, Growth, Area, __Luck__, Speed, Greed, Duration, Curse, Recovery, or Movement Speed
		They may select the same bonus multiple times
		(best way i can think of to represent it would be to make most of them green, and apply the red and green flashing effect to luck)
		
Horse
	Weapon:	
		Hats
	Stats:	
		Improved Movespeed
		Improved Projectile Amount
	
Megalo Impostor Rina
	Weapon:	
		[Hidden] Sharp Tongue
	Stats:	
		Improved Max Health
		Improved Movespeed
		Improved Might
		Improved Cooldown

**Comment by wraith309** [comment]
Weapons and Passives:
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/2ab286d1-7f34-4997-9ca8-fda267887c9f)
https://docs.google.com/spreadsheets/d/1m-cb_DVMaN8W8XkzjuP19U5ZfrlGu01kUzv3riRxwLY/edit?usp=sharing

**Comment by wraith309** [comment]
the Passive items are all functionally additional copies of existing vanilla weapons. They scale with the same stats and Arcana as the originals.
the only difference between them and the dlc passives is that they don't upgrade the same way.

**Comment by wraith309** [comment]
Finally the DLC stage itself starts with all of the "mini crewmate" passive items with the exception of mini horse, the weapon Lifesign Scan, the 2 rings and the 2 Metaglio pieces.

**Comment by Danmer** [comment]
This is really impressive work! Thank you very much for your research and shared results. It was incredibly helpful.
I added the DLC content based on your information. I haven't closed the topic for now, in case I forgot or missed something. Please, check if everything is ok when you have time.

**Comment by wraith309** [comment]
Are the Mini Crewmates supposed to highlight all of the weapons? i don't really see how having two different weapons would count as a synergy so I'm assuming that's a bug.

The DLC weapon evolutions are unities specifically, so they should cause the crewmates to disappear when acquired.

aside from those issues though, it looks fantastic. I can't wait to plan out some DLC builds

**Comment by wraith309** [comment]
Paranormal Scan also increases Magnet and Revives, so those should be highlighted.

**Comment by Danmer** [comment]
Well, yeah, this new mechanics are really confusing. Probably, I misunderstood your description and made them like Torrona Box (that's why having cooldown highlighted all weapons). So I had tried it myself, figured out how it works, and made the following changes:
- hovering dlc3-passives like weapons
- added icons of represented weapons (I hope it's gonna be more helpful than confusing)
- added extra slots for dlc3-passives to make them optional (otherwise, autoevolutions would make them always hidden)
- selecting dlc3-passives will autoselect corresponding weapons (because they can't be alone)
- removing dlc3-weapons will autoremove corresponding passives (because they can't be alone)

**Comment by wraith309** [comment]
> selecting dlc3-passives will autoselect corresponding weapons (because they can't be alone)

should probably set that to check if it's via stage items since they can be obtained on their own in that case. As is, the planner activates all the dlc3 weapons aside from hat whenever you select Polus Replica.
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/5f4d7e2f-8c0d-4134-bbe6-ce689caf6a9c)

**Comment by Danmer** [comment]
Oops. Didn't think about it. Fixed.

**Comment by wraith309** [comment]
Given no one's noticed any further issues (aside from the lack of rarity, but that could be separate and no one knows what the dlc weapon rarities are anyways) i think it's safe to close this.
