### ISSUE TITLE
Have X Beginning highlight amount scaling starting weapons (and whatever Trouser picks first if it has amount scaling)

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#28]
I checked the edge cases since Scorj-oni's lightning is easy enough to count.

Hidden weapons _do not_ count as a starting weapon, and Trouser's candy box choice does.

also, it works on characters with Blood Astronomia, which sort of implies that despite not needing them, things like garlic still have an amount stat, it just isn't used. which brings me to my other suggestion...

#29 having Blood Astronomia give amount and magnet scaling to their respective weapons.

**Comment by wraith309** [comment]
so characters who only start with hidden weapons do not benefit from beginning beyond the bonus it provides to joke weapons.

**Comment by wraith309** [comment]
I completely understand if this sounds like too much of a hassle though. Mainly because of Trouser

**Comment by Danmer** [comment]
Well noticed. Yeah, Trouser makes it a little harder. I made it this way for now:
- highlight character weapons if they are not hidden
- add candybox to the list of the arcana items (which is gonna mean that any selected weapon will be affected)
- add highlighting to the first weapon slot if trouser is selected

If you have any other suggestions to this list, feel free to reopen the issue.
