### ISSUE TITLE
Have Blood astronomia give it's respective weapons amount and Magnet Scaling

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#29]
Similarly to how Divine Bloodline gives Armor highlighting and Slash Gives Luck highlighting to relevant weapon, i think it would be informative for Blood Astronomia to do the same for magnet and luck.

I initially didn't think of this, but it seemed like a good idea when i realized that the blood Astronomia damaging zones are based on the amount value of the weapon itself, not just for your character. you can see this pretty easily by picking Blood Astronomia and Beginning on Poe or Christine since they make easy to count damaging zones based on their amount value, and beginning increases how many they produce.

![image](https://github.com/Danmer/vs-build-planner/assets/38050849/41ffaa0c-dcf9-45d1-b662-3e14abedb885)

**Comment by Danmer** [comment]
This is interesting idea! It's a bit strange to highlight a weapon that doesn't become stronger itself. Because it is arcana's damage, not garlic's. But I think it is acceptable assumption, so let's do it.
