### ISSUE TITLE
Page no longer working after latest build

### ISSUE THREAD

**Issue by Barragek0** [Danmer/vs-build-planner#3]
![image](https://user-images.githubusercontent.com/24503018/191263815-5b966d77-045c-454c-9ed7-92b9dbc25122.png)
![image](https://user-images.githubusercontent.com/24503018/191263921-4c4b7077-2bfc-4a55-9171-eb3131373386.png)

Have also tried using chrome and have the same issue.

Edit:
Console from chrome
![image](https://user-images.githubusercontent.com/24503018/191264147-99fb38a3-a70d-4ba0-9b82-001d0a139464.png)

**Comment by Danmer** [comment]
The last commit fixed this problem. Try CTRL + F5 to refresh your cache.
