### ISSUE TITLE
Bracelets keep the effects of previous arcana when evolved.

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#33]
I always thought they should work that way, and it turns out they actually do, and the wiki is just lying.
the misleading icons on the arcana cards don't help matters either.
Testing was pretty conclusive though. i got jail of crystal, and it turned enemies blue before killing them on all 3 versions of the bracelet.
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/a4d91791-e74c-4c7a-af6e-57bad03e4566)
so it's this:
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/90c1815f-fe5e-489a-b710-d9b32793477c)
not this:
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/7aad58b8-02e5-4653-8d06-dbee472ac898)

**Comment by Danmer** [comment]
Cool. Always wanted to know that :)
