### ISSUE TITLE
Minnah does not benefit from the stat oscillation from arcanas V, XVII, XVIII

### ISSUE THREAD

**Issue by Danmer** [Danmer/vs-build-planner#36]
Probably, these arcanas shouldn't highlight anything for Minnah

> Minnah does not benefit from the stat oscillation from Chaos in the Dark Night (V), Lost & Found Painting (XVII) and Boogaloo of Illusions (XVIII), as they require the character to not have value in the sineStat attributes to set their own value while the changing stats already occupied them. It does not override them either; however, she can still benefit from the additional stats every level.
https://vampire-survivors.fandom.com/wiki/Minnah_Mannarah

**Comment by wraith309** [comment]
I disagree that those arcana require changing. primarily because of the last sentence
> It does not override them either; however, she can still benefit from the additional stats every level.

I personally pretty much only ever take those arcana for the additional +1% to their respective stat per level, and that part at least is unchanged when using her.

**Comment by wraith309** [comment]
However, If you still think those stats should not be highlighted with those Arcana, then for the sake of consistency i should at least point out that McCoy-Oni's Area stat works the same way as Minnah's

**Comment by Danmer** [comment]
You're right. 1% is more important.
