### ISSUE TITLE
Divine Bloodline's Max HP scaling isn't limited to just the listed weapons.

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#48]
all weapons that care about might benefit from divine bloodline max hp scaling. Only the armor bonus cares if it's one of divine bloodline's listed weapons or not.

**Comment by Danmer** [comment]
Please, could you check if I understand you correctly. Do these screenshots represent the right behaviour?

![2024-01-28_17-31-12](https://github.com/Danmer/vs-build-planner/assets/390169/61c7391d-f004-4fc5-9d53-6c28a89b85a8)

![2024-01-28_17-44-49](https://github.com/Danmer/vs-build-planner/assets/390169/f60e67a2-0c6a-46a6-86e7-caf80f9e5da7)

**Comment by wraith309** [comment]
yup! the description says
> Armor also affects listed weapons' damage and reflects enemy damage. 
> Character gains bonus damage depending on missing Health. 
> Defeating enemies with retaliatory damage gives +0.5 Max Health.
