### ISSUE TITLE
Allow everyone to choose one additional Arcana for inverse mode builds.

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#51]
Inverse mode lets you buy an extra 4th Arcana from the merchant, and is balanced around it's inclusion. (or a 5th or 6th if you're using Infernas or Sigma respectively)

**Comment by wraith309** [comment]
You could even make the stage pictures turn upside down when a character's build goes over their normal Arcana limit. that 's more an amusing suggestion than the actual purpose of this issue though😛

**Comment by Danmer** [comment]
I love this idea!
