### ISSUE TITLE
Sigma got too many extra Arcana slots from the most recent update.

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#55]
![vs-build_2024-02-11T19-03-11](https://github.com/Danmer/vs-build-planner/assets/38050849/b030b8d2-af66-42a6-beee-cf7fba2166ec)

She should cap out at 6 arcana on inverse levels.

**Comment by wraith309** [comment]
![vs-build_2024-02-11T19-48-47](https://github.com/Danmer/vs-build-planner/assets/38050849/7df9e394-b213-4b0c-9c10-a88bd4f4aad0)

Still one too many 💀

**Comment by Danmer** [comment]
Sorry, it was made in a hurry.
