### ISSUE TITLE
The horizontal alignment of the bottom row when exceeding 3 arcana looks whack.

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#56]
![vs-build_2024-02-11T19-06-08](https://github.com/Danmer/vs-build-planner/assets/38050849/929c792e-96b4-46be-8afd-dd2ac9dc3583)

**Comment by Danmer** [comment]
Should be ok for two and even three rows now.

![vs-build_2024-05-09T13-15-47](https://github.com/Danmer/vs-build-planner/assets/390169/89a69c23-2a3e-4934-a852-167c84432904)
![vs-build_2024-05-09T13-15-39](https://github.com/Danmer/vs-build-planner/assets/390169/34f8fe2b-d8df-4a24-a3ef-8e48263e1ef5)
