### ISSUE TITLE
New Patch, new content

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#58]
1 New Map
	Space 54
	Contains:
		Candelabrador, Empty Tome, Phas3r
		
2 New Characters
	Space Dude
	Starts With: Phas3r
	Stats: Movespeed, (and his unique ability scales with cooldown)
	
	Robbert
	Starts With: Pako Battiliar
	Stats: Health, Recovery, Armor, Movespeed

4 New Weapons
	Phas3r (evolves into Photonstorm)
	Evolution requirements: Empty Tome
	Scaling: Might, Area, Cooldown, Amount
	
	Photonstorm
	Scaling: Might, Area, Cooldown, Amount, Luck
	
	Pako Battiliar (evolves into Mazo Familiar)
	Evolution requirements: Hollow Heart
	Scaling: Might, Speed, Area, Cooldown, Amount
	
	Mazo Familiar
	Scaling: Might, Speed, Area, Cooldown, Amount

**Comment by wraith309** [comment]
whoops, didn't meant for that to be formatted.
ah well, it's still readable.

**Comment by Danmer** [comment]
As usual, thank you for your helpful information. I will leave the issue open until you confirm if everything is ok.

**Comment by wraith309** [comment]
I've double checked all of the: weapons, characters, maps, and arcana, and aside from Space Dude who's description reads "May occasionally activate all weapons twice depending on Cooldown" they all look correct

**Comment by Danmer** [comment]
> aside from Space Dude who's description reads "May occasionally activate all weapons twice depending on Cooldown"

What's wrong with this description?

**Comment by wraith309** [comment]
he's missing cooldown scaling

**Comment by wraith309** [comment]
I forgot about armor.
the two bat weapons both retaliate, so they should both have armor scaling.

**Comment by wraith309** [comment]
looks complete. 👍
