### ISSUE TITLE
Match default sorting to that ingame

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#61]
Change default organization to match the character select screen and collection menus in-game.

This is obviously more or a personal preference thing, but i feel like it would be easier to navigate if the build planner was organized in the same way as the character select screen and collection menus. especially when you have a build planned and need to start sealing things in game.

For the Collection menu that would be:

![image](https://github.com/Danmer/vs-build-planner/assets/38050849/66acc75d-f71f-495f-9ae9-6c14abcd9965)
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/1c8a8c84-71b5-49ae-84d2-47fb4a1a5212)

Weapons:
Whip
Magic Wand
Knife
Axe
Cross
King Bible
Fire Wand
Garlic
Santa Water
Runetracer
Lightning Ring
Pentagram
Peachone
Ebony Wings
Phiera Der Tuphello
Eight The Sparrow
Gatti Amari
Song of Mana
Shadow Pinion
Clock Lancet
Laurel
Vento Sacro
Bone
Cherry Bomb
Carréllo
Celestial Dusting
La Robba
Greatest Jubilee
Bracelet

Pako Battiliar
Victory Sword
Flames of Misspell
Glass Fandango
Phas3r

Silver Wind
Four Seasons
Summon Night
Mirage Robe
Night Sword
Mille Bolle Blu
108 Bocce

SpellString
SpellStream
SpellStrike
Eskizzibur
Flash Arrow
Prismatic Missile
Shadow Servant
Party Popper

Report!
Lucky Swipe
Lifesign Scan
Just Vent
Clear Debris
Sharp Tongue
Science Rocks
Hats

Evolutions:
Bloody Tear
Holy Wand
Thousand Edge
Death Spiral
Heaven Sword
Unholy Vespers
Hellfire
Soul Eater
La Borra
NO FUTURE
Thunder Loop
Gorgeous Moon
Vandalier
Phieraggi
Vicious Hunger
Mannajja
Valkyrie Turner
Infinite Corridor
Crimson Shroud
Fuwalafuwaloo
Bi-Bracelet
Tri-Bracelet

Mazo Familiar
Sole Solution
Ashes of Muspell
Celestial Voulge
Photonstorm

Festive Winds
Godai Shuffle
Echo Night
J'Odore
Muramasa
Boo Roo Boolle

SpellStrom
Legionnaire
Milionaire
Luminaire
Ophion

Emergency Meeting
Crossed Wires
Paranormal Scan
Unjust Ejection
Clear Asteroids
Impostongue
Rocket Science

![image](https://github.com/Danmer/vs-build-planner/assets/38050849/b7f0a6ff-c686-4cc5-9ffb-60dfc02cbc44)

Passives:
Spinach
Armor
Hollow Heart
Pummarola
Empty Tome
Candelabrador
Bracer
SpellBinder
Duplicator
Wings
Attractorb
Clover
Crown
Stone Mask
Skull O'Maniac
Tirajisú
Torrona's Box
Silver Ring
Gold Ring
Metaglio Left
Metaglio Right

Academy Badge

Mini Crewmate
Mini Engineer
Mini Ghost
Mini Shapeshifter
Mini Guardian
Mini Imposter
Mini Scientist
Mini Horse

for characters that would be:
The base game characters:

![image](https://github.com/Danmer/vs-build-planner/assets/38050849/45e7680f-72b1-49b9-b071-249624774e34)
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/4398e2c8-df1c-4973-a2d1-577019726bc8)
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/2bd9d7d3-47a6-49f4-a614-829f80e4d6ff)
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/7af2b725-0f27-4da7-9cae-9840f649dcb1)

Antonio
Imelda
Pasquelina
Gennaro
Arca
Porta
Lama
Poe
Clerici
Commario
Krocji
Christine
Pugnala
Giovana
Poppea
Concetta
Mortaccio
Cavallo
Ramba
O'Sole
Ambroje
Gallo
Divano
Zi'Assunta
Exdash
Roastie
Smith IV
Random
Marrabbio
Avatar
Minnah
Leda
Cosmo
Peppino
Trouser
MissingN□
Gains
Gyorunton
Red Death
Sigma
Robbert
She-Moon
Space Dude
Rose
Scorej-Oni

Moonspell characters:

![image](https://github.com/Danmer/vs-build-planner/assets/38050849/f696ee20-df45-48c5-87c2-48f5848d1f6f)

Miang
Menya
Syuuto
Babi-Onna
McCoy-Oni
Megalo Menya
Megalo Syuuyo
Gav'Et-Oni

Foscari characters:

![image](https://github.com/Danmer/vs-build-planner/assets/38050849/e4b10919-3bf1-43dd-826e-fc0b3ec56a2a)

Eleanor
Maruto
Keitha
Luminaire
Genevieve
Je-Ne-Viv
Sammy
Rottin'Ghoul

Amogus characters:

![image](https://github.com/Danmer/vs-build-planner/assets/38050849/2eb89025-640e-4e18-8f24-9d1f6c44cdc6)

Crewmate
Engineer
Ghost
Shapeshifter
Guardian
Imposter
Scientist
Horse
Megalo Imposter

**Comment by wraith309** [comment]
To be clear, i'm not suggesting that the base weapon and evolutions be merged, just that they get reordered to match the order they show up in the collection menu

**Comment by wraith309** [comment]
oh, and stages too:

Mad Forest
Inlaid Library
Dairy plant
Gallo Tower
Capella Magna

Il Molise
Moongolow
Green Acres
The Bone Zone
Boss Rash
Whiteout
Space 54
Bat Country
Astral Stair
Tiny Bridge

Mt.Moonspell
Lake Foscari
Abyss Foscari
Polus Replica

**Comment by Danmer** [comment]
Should be matched now
