### ISSUE TITLE
Allow disabling of DLC content

### ISSUE THREAD

**Issue by uqs** [Danmer/vs-build-planner#64]
Hey there, please add a filter to turn on/off the 3 (?) current DLC content.

There was too much stuff going on, so for now I disabled all the DLC in the game to focus on getting all core achievements and so on, but the planner doesn't even fit on one screen and I furiously need to scroll up and down, dropping the DLCs would help.

Or maybe, once a character has been selected, collapse all other characters?

Or maybe the top build info can hover and stay at the top of the screen always?

Maybe it can move to the side (like it's in the game?) I have a widescreen monitor and the webpage doesn't make use of the extra horizontal space, so I think having the selected items hover on the left hand side of the screen could also work well.

Thank you for considering!

**Comment by Danmer** [comment]
I absolutely agree with you. I have added filtering DLC content for the beginning. Your other suggestions about collapsing and moving selected items to the side are also very good. I will definitely implement something like this in the future updates. Thank you.
