### ISSUE TITLE
Add patch 1.10 content

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#66]
Namely 2 new characters and 2 new weapons

**Comment by wraith309** [comment]
the new weapons share the same Arcana and Stats

Santa Javelin 
 evolves into 
Seraphic Cry

Arcana: I, II, III, XVI

Stats:
Might
Area
Amount
Duration
Cooldown
Evolves with Luck

**Comment by wraith309** [comment]
there are also new stages but they don't have guaranteed stage items so eh...

**Comment by wraith309** [comment]
the First new character:
Santa
+Armor
+Luck
Starting weapon:
 Santa Javelin

**Comment by wraith309** [comment]
Second new character:
Gyoruntin
+Health
+Armor
+Movespeed
+Curse
Starting weapon:
NO FUTURE

**Comment by Danmer** [comment]
Thank you for this and other opened issues. Finally I have found some time to fix part of them and add 1.10 content. I hope nothing is missed.

**Comment by wraith309** [comment]
this one's my bad, i said it was impacted by the Gemini arcana but forgot to mention the Gemini weapon. if you include that, there are technically 3 new weapons. the mirrored Santa Javelin is called Levelin'Eh

**Comment by Danmer** [comment]
> forgot to mention the mirrored Santa Javelin

It is already added as a counterpart if Gemini is selected. Should it be added somewhere else?

![vs-build_2024-05-09T16-49-26](https://github.com/Danmer/vs-build-planner/assets/390169/5b4ff279-c150-4b15-a93d-15f04020339c)

**Comment by wraith309** [comment]
huh, it's there now. i think maybe i just didn't see it before as a consequence of #67

**Comment by wraith309** [comment]
It turns out one of the 1.10 stages does in fact have stage items, the fact that they're hidden behind levers just makes it a lot harder to verify for certain without repeatedly running the stage. Since it does in fact have stage items, it should probably be added to the list of stages in the planner.

Laborratory contains:
Santa Javelin
Metaglio Left
Metaglio Right

**Comment by Danmer** [comment]
Added lab, but I'm not sure about the stage items.

I was told in Discord that bible, cross, water, arma dio and rings are also dropped there.

Also the wiki says there are:
Passives: Clover, Attractorb, Spellbinder, Arma Dio
Weapons: Cross, King Bible, Santa Javelin, Santa Water
And 4 hidden stage items if the player has obtained the Yellow Sign: Silver Ring, Metaglio Right, Gold Ring, Metaglio Left

**Comment by wraith309** [comment]
damn, must just be my luck then. good to know there are more items.
