### ISSUE TITLE
starting weapons don't evolve properly

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#67]
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/2171edf0-a528-4d7d-8d92-00506cf4ef8c)
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/dfc0827e-f2cc-43b1-84ea-c02e0fccc4a6)

**Comment by Danmer** [comment]
Sorry, should be fixed. Also now you can select unevolved weapons for characters with starting evolutions.

![image](https://github.com/Danmer/vs-build-planner/assets/390169/fc36426b-7628-423c-9cc9-8cba6156dd83)
