### ISSUE TITLE
Add DLC 4 Operation Guns

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#68]
i haven't checked what all the content is yet, but i figured i could at least open the issue.

**Comment by Danmer** [comment]
Omg, so much new content. It's not gonna look well. Probably we will need some changes in the page layout. Hm...

**Comment by wraith309** [comment]
weapons:
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/be0b1a06-01ca-4cd8-8d4c-03fe3504c0df)

**Comment by wraith309** [comment]
Characters:

Bill Rizer
Starts with: Long gun
Improves max health
Improves Projectile speed
Improves might

Lance Bean
Starts with: Short Gun
Improves max health
Improves Projectile speed
Improves cooldown

Ariana
Starts with: Spread Shot
Improves Move speed
Improves Projectile speed
Improves Armor
Improves Growth

Lucia Zero
Starts with: C-U-Laser
Improves recovery
Improves move speed
Improves revival

Brad Fang
Starts with: Firearm
Improves max health
Improves might
has a temporary buff at low hp that does the following (not sure if temporary buffs are included or not)
Improves cooldown
Improves movespeed
Improves Projectile speed

Browny
Starts with: Sonic Bloom
Improves Max health
Improves Armor
Improves Move Speed
Improves Luck
Improves Cooldown
Improves Area

Sheena Etranzi
Starts with: Blade Crossbow
Improves Recovery
Improves Move Speed
Improves Cooldown

Probotector
Starts with: Prism Lass
Improves Max Health
Improves Armor
Improves Might

Stanley
Starts with: Homing Miss
Improves Max Health
Improves Armor
Improves Might

Newt Plissken
Starts with: Diver Mines
Improves Max Health
Improves Movespeed
Improves Luck
Improves Projectile Speed
Improves Might

Colonel Bahamut
Starts with: Metal Claw
Improves Max Health
Improves Armor
Improves Move Speed
Improves Might
Improves Magnet
Improves Greed
Improves Curse

Simondo Belmont
Starts with: no weapon
Improves Amount

**Comment by wraith309** [comment]
1 new stage has stage items 
Neo Galuga
![image](https://github.com/Danmer/vs-build-planner/assets/38050849/586c3d12-e08a-4cc0-bd5d-853cf31397cd)

**Comment by Danmer** [comment]
Added DLC 4. I checked twice if everything is ok. But there is a lot of stuff so I could easily miss something.

Question: should we highlight Luck for Prism Lass or/and its upgrade since it has a chance to freeze?

**Comment by wraith309** [comment]
i would add it to be consistent, since you've already added it to jail of crystal on other weapons. and that's also a luck based chance to freeze

**Comment by wraith309** [comment]
dlc4 content is missing sprites on planner2
