### ISSUE TITLE
Characters with passive weapons are displayed inconsistantly

### ISSUE THREAD

**Issue by wraith309** [Danmer/vs-build-planner#7]
![image](https://user-images.githubusercontent.com/38050849/219480420-c047d212-fa39-443e-8de1-ee415f8a7f3a.png)
![image](https://user-images.githubusercontent.com/38050849/219480463-70c805f5-4e35-4d1c-88cd-0cc96cb9070b.png)
![image](https://user-images.githubusercontent.com/38050849/219480492-b478c8f7-aeb5-4527-ae6c-ecbe43fe8344.png)
All three of the above characters start with an invisible copy of their given weapon, but none of them share a common means of displaying their starting weapon in the build planner. Personally, I think setting them up to display in the same manner as Cosmo would make the most sense.

**Comment by Danmer** [comment]
@wraith309 thank you for your suggestion. I agree with you and made an update. Their started weapons are "passive" as well now.
